### PR TITLE
ENH drop pycamb and python 2

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Review by cmbant — COMMENTED** [review]
Looks good to me, though the checking process still seems to be mentioning "win win_python2.7" etc?

**Comment by beckermr** [comment]
Yeah something went weird with the recipe rendering. I will merge when it looks correct.

**Comment by beckermr** [comment]
It turned off all of the linux builds. LOL

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
